name: Docker image builder
on:
  push:
    branches: [ main ]
    paths: 
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup docker context for buildx
      id: buildx-context
      run: docker context create builders
    -
      # Setting up Docker Buildx with docker-container driver is required
      # at the moment to be able to use a subdirectory with Git context
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 
      with:   
        endpoint: builders
        buildkitd-flags: --debug
    -
      name: Login to containers.github.alloptions.systems
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        builder: default
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest