name: Part 2 - Cython

on:
  push:
    branches: [ main ]
    paths:
      - 'part_2/cython_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_2/cython_solution/**'
  workflow_dispatch:   
    
jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}:latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      working-directory: './part_2/cython_solution'
      run: python3 setup.py build_ext --inplace
    - name: upload Exchange
      uses: actions/upload-artifact@v4
      with:
        name: part_2_cython	
        path: |
          ./part_2/cython_solution/Exchange.so
          ./part_2/cython_solution/runner 
