name: Part 1 - Python

on:
  push:
    branches: [ main ]
    paths:
      - 'part_1/python_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_1/python_solution/**'
  workflow_dispatch:
     
jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}:latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      working-directory: './part_1/python_solution'
      run: python3 -m py_compile *.py
    - name: upload Exchange
      uses: actions/upload-artifact@v4
      with:
        name: part_1_python	
        path: ./part_1/python_solution/*.py 
    - name: upload runner
      uses: actions/upload-artifact@v4
      with:
        name: part_1_python	
        path: ./part_1/python_solution/runner 
